### ISSUE TITLE
Open sans medium (500) weight missing

### ISSUE THREAD

**Issue by Spy-Seth** [fontsource/google-font-metadata#33]
**Describe the bug**
The Open sans medium (500) weight is missing in the generated metadata for this font. 

This weight is listed on the Open sans google font page: https://fonts.google.com/specimen/Public+Sans 
When I download the font I could also see a dedicated file. 

This lead to have the font missing in the https://github.com/fontsource/fontsource packages.

**Expected behavior**
All the google font weights should be declared

**Comment by DecliningLotus** [comment]
Hey there,

I'm not sure where you're locating this error?

Open Sans does **not** have a 500 weight, as shown here: https://fonts.google.com/specimen/Open+Sans
Public Sans does have a 500 weight, which you linked above. 

Fontsource seems to be mirroring both options just fine. Perhaps you got confused between the two?

**Comment by Spy-Seth** [comment]
Ho... right I do confuse both font :sob:  Sorry for this :sweat_smile:
